MeetUp/ViewModels/Profil.cs
using MeetUp.DAL;
using MeetUp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MeetUp.ViewModels
{
    public class Profil
    {
        public List<User> GetUser()
        {
            MeetUpContext baza = new MeetUpContext();
            List<User> lista = baza.Users.ToList();
            return lista;
        }

        public User ZnajdzUsera(int id)
        {
            User c = new User();
            MeetUpContext baza = new MeetUpContext();
            baza.Users.Attach(c);
            c = baza.Users.Find(id);
            return c;
        }
        public List<Event> GetUserEvent(User u)
        {
            MeetUpContext baza = new MeetUpContext();
            List<Event> lista = baza.Events.Where(x => x.User.userId == u.userId).ToList();
            return lista;
        }
    }
}

MeetUp/Controllers/EventyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MeetUp.DAL;
using MeetUp.Models;

namespace MeetUp.Controllers
{
    public class EventyController : Controller
    {
        private MeetUpContext db = new MeetUpContext();

        // GET: Eventy
        public ActionResult Index()
        {
            var events = db.Events.Include(x => x.User);

            return View(events.ToList());
        }

        // GET: Eventy/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }


        // GET: Eventy/Create
        public ActionResult Create()
        {
            ViewBag.userId = new SelectList(db.Users, "userId", "login");
            return View();
        }


        // POST: Eventy/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Event_Id,Name,number,Place,Date,userId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                int id = Int32.Parse(Session["userId"].ToString());
                @event.User = db.Users.FirstOrDefault(x => x.userId == id);

                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.userId = new SelectList(db.Users, "userId", "login", @event.userId);
            return View(@event);
        }

        // GET: Eventy/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            ViewBag.userId = new SelectList(db.Users, "userId", "login", @event.userId);
            return View(@event);
        }

        // POST: Eventy/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Event_Id,Name,number,Place,Date,userId")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.userId = new SelectList(db.Users, "userId", "login", @event.userId);
            return View(@event);
        }

        // GET: Eventy/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Eventy/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MeetUp/Controllers/HomeController.cs
using Facebook;
using MeetUp.DAL;
using MeetUp.Models;
using MeetUp.ViewModels;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MeetUp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //DAL.MeetUpContext db = new DAL.MeetUpContext();
            return View();
        }
        public ActionResult StworzEvent()
        {    
                return View();
        }

        [HttpPost]
        public ActionResult StworzEvent(Event eve)
        {
            if (!ModelState.IsValid)
            {
                return View("StworzEvent", eve);
                
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
            
        }
        public ActionResult Profil()
        {
            int id;
            try
            {
                id = Int32.Parse(Session["userId"].ToString());
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
            //id = Int32.Parse(Session["userId"].ToString());
            dynamic mymodel = new ExpandoObject();
            Profil ktos = new Profil();
            User c = ktos.ZnajdzUsera(id);
            mymodel.User = c;
            mymodel.Events = ktos.GetUserEvent(c);
            return View(mymodel);
        }

        [HttpGet]
        public ActionResult Rejestracja(int id = 0)
        {
            User ktos = new User();
            return View(ktos);
        }

        [HttpPost]
        public ActionResult Rejestracja(User ktos)
        {
            User ktos1 = new User();
            ktos1 = ktos;
            UserAdd user = new UserAdd();
            List<User> lista = user.GetUser();
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                if (lista.Any(u => u.login == ktos.login))
                {
                    ModelState.AddModelError("login", "Ten login jest już zajęty!");
                    return View("Rejestracja", ktos);
                }
                else if (ktos.password.Count() < 8)
                {
                    ModelState.AddModelError("password", "Hasło musi mieć co najmniej 8 znaków!");
                    return View("Rejestracja", ktos);
                }
                else
                {
                    user.AddUser(ktos1);
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Logowanie(string ReturnUrl)
        {
            ViewBag.ReturnUrl = ReturnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Logowanie(User user, string ReturnUrl)
        {
            MeetUpContext baza = new MeetUpContext();
            var daneUsera = baza.Users.Where(k => k.login == user.login && k.password == user.password).FirstOrDefault();
            UserAdd ktos = new UserAdd();
            List<User> lista = ktos.GetUser();
            //if (daneUsera == null)
            //{
            //    ModelState.AddModelError("login", "Błędny login lub hasło");
            //    return View("Logowanie", user);
            //}
            if (!lista.Any(k => k.login == user.login && k.password == user.password))
            {
                ModelState.AddModelError("password", "Błędny login lub hasło");
                return View("Logowanie", user);
            }
            else
            {
                Session["userId"] = daneUsera.userId;
                Session["login"] = daneUsera.login;
                FormsAuthentication.SetAuthCookie(user.login, false);

                if (Url.IsLocalUrl(ReturnUrl))
                {
                    return Redirect(ReturnUrl);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }

        }

        public ActionResult Wyloguj()
        {
            int Id = (int)Session["userId"];
            Session.Abandon();
            return RedirectToAction("Logowanie", "Home");
        }
        //logowanie fb
        private Uri RediredtUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }
        
        [AllowAnonymous]
        public ActionResult Facebook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = "1161864983966121",
                client_secret = "d5eea1154e79fb70a17bd8525708a5e1",
                redirect_uri = RediredtUri.AbsoluteUri,
                response_type = "code",
                scope = "email"
            });
            return Redirect(loginUrl.AbsoluteUri);
        }
        
        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = "1161864983966121",
                client_secret = "d5eea1154e79fb70a17bd8525708a5e1",
                redirect_uri = RediredtUri.AbsoluteUri,
                code
            });
            var accessToken = result.access_token;
            
            fb.AccessToken = accessToken;
            dynamic me = fb.Get("me?fields=link,first_name,last_name,email,picture,age_range");
            string email = me.email;
            User user = new User()
            {
                age = 20,
                name = me.first_name,
                surname = me.last_name,
                login = me.id,
                password = "5QgboDCEJZDSApBqgZ5V",
                confirmedpassword = "5QgboDCEJZDSApBqgZ5VF"
            };

            UserAdd users = new UserAdd();
            List<User> lista = users.GetUser();
            //if(!lista.Any(u => u.login == user.login))
                Rejestracja(user);
            Logowanie(user, "/home/index");

            FormsAuthentication.SetAuthCookie(email, false);
            return RedirectToAction("Index", "Home");
        }
    
    }
}

MeetUp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MeetUp/Views/Home/Archiwium.cshtml
@model MeetUp.ViewModels.ArchiwEvent
@{
    ViewBag.Title = "Archiwium";
}

<h2>Archiwium</h2>

<div>
    @foreach (var e in Model.Events)
    {

        <div style="text-align:center; color:lightgrey; font-size:x-large; font:800">
            @Html.DisplayFor(m => e.Name)
        </div>

        <div style="text-align:center; font-size:medium">
            <p style="color:white">@Html.DisplayFor(m => e.palce)</p>
        </div>
        <div style="text-align:center; font-size:medium">
            <p style="color:white">@Html.DisplayFor(m => e.Date)</p>

        </div>
        <div style="text-align:center">
            <b style="color:black; font:800">Organizator: @Html.DisplayFor(m => e.User.login)</b>
        </div>
        <div style="text-align:center">
            @Html.ActionLink("Zobaz wiecej", "EventDetails");
        </div>
        <div style="height:40px"></div>
    }
</div>

MeetUp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MeetUp/Views/Home/EditUser.cshtml
@model MeetUp.Models.User

@{
    ViewBag.Title = "EditUser";
}

<h2>EditUser</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.userId)

        <div class="form-group">
            @Html.LabelFor(model => model.login, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.login, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.login, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.surname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.surname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListaUserow")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MeetUp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE HTML>
<html lang="pl">
<head>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
    <meta charset="utf-8" />

    <style>

        .button {
            background-color: saddlebrown;
            border: none;
            color: white;
            padding: 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }


        img {
            width: 125%;
        }

        input[type=text] {
            width: 100%;
            border: 2px;
            border-radius: 4px;
            margin: 8px 0;
            outline: none;
            padding: 8px;
            margin-left: 500px;
            box-sizing: border-box;
            transition: .3s;
            background-color: #363636;
            color: coral;
            font-size: 20px;
        }

            input[type=text]:focus {
                border-color: dodgerBlue;
                box-shadow: 0 0 8px 0 dodgerBlue;
            }


        body {
            background-color: #535353;
        }

        #container {
            width: 1200px;
            height: 700px;
            margin-left: auto;
            margin-right: auto;
            background-color: #535353;
        }

        #logo {
            background-color: #52527a;
            color: white;
            text-align: center;
            padding: 15px;
            margin-bottom: 10px;
        }



        #content {
            background-color: indigo;
            float: left;
            padding: 30px;
            width: 600px;
            height: 600px;
            font-size: 60px;
            color: saddlebrown;
            text-align: center;
            vertical-align: middle;
        }

        #gadget {
            float: left;
            width: 600px;
            height: 600px;
            background-color: dimgray;
            text-align: center;
        }

        #footer {
            clear: both;
            background-color: #003300;
            color: white;
            text-align: center;
            padding: 20px;
            margin-top: 10px;
        }
    </style>

</head>

<body>

    <div id="container">


        <div class="logo">
            <input type="text" placeholder="Znajdz miejsce">
        </div>


        <div id="content">

            <h1>
                MEETUP:
            </h1>
            <h1>
                YOUR EVENT
            </h1>
            <h1>
                PLANNER
            </h1>
            <button class="button button3">Learn More</button>
        </div>

        <div id="gadget">
            <img src="~/zdjecia/mtp.png" />
        </div>


    </div>

</body>
</html>

MeetUp/Views/Home/ListaEventowAdmin.cshtml
@model IEnumerable<MeetUp.Models.Event>

@{
    ViewBag.Title = "ListaEventowAdmin";
}

<h2>Lista wszystkich eventów</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.number)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Place)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.userId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.number)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Place)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.userId)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Event_Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Event_Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Event_Id })
        </td>
    </tr>
}

</table>

MeetUp/Views/Home/ListaUserow.cshtml
@model IEnumerable<MeetUp.Models.User>

@{
    ViewBag.Title = "ListaUserow";
}

<h2>Lista wszystkich userów</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.login)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.age)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.login)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.surname)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.age)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditUser", new { id=item.userId }) |
            @Html.ActionLink("Delete", "DeleteUser", new { id=item.userId })
        </td>
    </tr>
}

</table>

MeetUp/Views/Home/Logowanie.cshtml
@model MeetUp.Models.User

@{
    ViewBag.Title = "Logowanie";
}

<h2>Logowanie</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.login, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.login, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.login, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Sign in" class="btn btn-default" />
        </div>
    </div>
    <div>
        <hr />
        Zaloguj sie przez: @Html.ActionLink("Facebook", "Facebook", "Home")
    </div>
</div>
}

MeetUp/Views/Home/Profil.cshtml
@using MeetUp
@model dynamic
@{
    ViewBag.Title = "Profil";
}

<h2>Profil</h2>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/bootstrap.css">
    <title>Registration</title>
</head>
<body style="background-color:indigo; margin: 0; padding: 0">
    
    <h2 style="text-align:center; color:white">Twój profil</h2>
    <div style="height:40px"></div>
    <div style="color:black">
        @using (Html.BeginForm())
        {
            <div style="height:40px"></div>
            <table>
                <tr class="form-group" style="height:40px">
                    <td style="text-align: right; font:800; font-size:large; color: white">Login: </td>
                    <td style="text-align: left; font:800; font-size:large; color: white">@Model.User.login</td>
                </tr>
                <tr class="form-group" style="height:40px">
                    <td style="text-align: right; font:800; font-size:large; color: white">Imię: </td>
                    <td style="text-align: left; font:800; font-size:large; color: white">@Model.User.name</td>
                </tr>
                <tr class="form-group" style="height:40px">
                    <td style="text-align: right; font:800; font-size:large; color: white">Nazwisko: </td>
                    <td style="text-align: left; font:800; font-size:large; color: white">@Model.User.surname</td>
                </tr>
                <tr class="form-group" style="height:40px">
                    <td style="text-align: right; font:800; font-size:large; color: white">Wiek: </td>
                    <td style="text-align: left; font:800; font-size:large; color: white">@Model.User.age</td>

                </tr>

            </table>
        }
        <table class="table" style="font:800; font-size:large; color: white">
            <tr>
                <th>Id</th>
                <th>Nazwa</th>
                <th>Liczba biletów</th>
                <th>Miejsce</th>
                <th>Data</th>
                <th></th>
            </tr>
            @foreach (var e in Model.Events)
            {
            <tr>
                <td>
                    @e.Event_Id
                </td>
                <td>
                    @e.Name
                </td>
                <td>
                    @e.number
                </td>
                <td>
                    @e.Place
                </td>
                <td>
                    @e.Date
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", "Eventy") |
                    @Html.ActionLink("Details", "Details") |
                    @Html.ActionLink("Delete", "Delete")
                </td>
            </tr>
            }
        </table>


    </div>
</body>
</html>

MeetUp/Views/Home/Rejestracja.cshtml
@model MeetUp.Models.User

@{
    ViewBag.Title = "Rejestracja";
}

<h2>Rejestracja</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>User</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.login, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.login, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.login, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.confirmedpassword, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.confirmedpassword, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.confirmedpassword, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.surname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.surname, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.surname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>